---
title: "RCLCO Skill Share"
author: "Dana Schoewe"
date: "3/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load libraries needed for analysis
library(here)
library(tidyverse)
library(plotly)
library(ggmap)
library(leaflet)
library(tidycensus)
library(tigris)
library(sf)
library(htmltools)
library(broom)
library(RColorBrewer)
library(DT)
options(tigris_use_cache = TRUE)
```

## Making Cool Color Maps In R With Census Data

```{r, echo=TRUE}
#understand census variables
#v_list18 <- load_variables(2018, "acs5", cache = TRUE)
#View(v_list18)
#search "median household income"
#result is B19013_001

#get income data for CA pumas
CAinc <- get_acs(geography = "public use microdata area",
                    variables = c(med_inc = "B19013_001"),
                    year = 2018,
                    output = "wide",
                    state = "CA",
                    geometry = FALSE)

#get CA pumas shapefile and convert to sf object
CApumas <- pumas(state = "CA") %>% 
  as(., "sf")
#plot(CApumas)

#join data to shapefiles and transform to 4326 projection
CAjoin <- left_join(CApumas, CAinc, by = c("GEOID10" = "GEOID"))
st_crs(CAjoin)
CAjoin_map <- st_transform(CAjoin, crs = "+init=epsg:4326")

#filter for LA County Only
LACounty <- CAjoin_map %>% 
  filter(str_detect(NAME, "Los Angeles County"))

#create color palettes for mapping
#display.brewer.all()
cool_pal <-colorBin(palette = "YlGnBu", domain = LACounty$med_incE, bins = c(0,50000,75000,100000,500000))

#build bins cloropleth map
map2 <- leaflet() %>% 
  addProviderTiles("CartoDB", group = "Carto") %>% 
  addPolygons(data = LACounty,
              weight = 1,
              color = "black",
              popup = ~paste0("<strong>PUMA: </strong>", NAME, "<br><strong>2018 Median Income: </strong>", scales::dollar(med_incE)),
              fillColor = ~cool_pal(med_incE),
              fillOpacity = 0.7) %>% 
  addLegend(position = "bottomleft",
            pal = cool_pal,
            values = LACounty$med_incE,
            labFormat = labelFormat(prefix = "$"),
            title = "Median Income")
map2

```

